import type { Metadata } from "next";
import { Outfit } from "next/font/google";
import "./globals.css";
import SideNav from "@/components/SideNav";
import Shell from "@/components/Shell";

const outfit = Outfit({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Thejus Rajendran | Product Designer",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={outfit.className}>
      <body className="bg-gray-100 h-screen flex gap-6 p-8">
        <div className="grow-0 w-64 h-full">
          <SideNav />
        </div>
        <div className="grow h-full">
          <Shell>{children}</Shell>
        </div>
      </body>
    </html>
  );
}
